### ISSUE TITLE
App crashes without leaving any output

### ISSUE THREAD

**Issue by YoavLevi** [travisfoley/dfirtriage#10] opened 2022-04-15 14:45 UTC
After a privileged execution with the command line:

"DFIRtriage.exe -nm -elpa -elf"

The following error occurs:

Traceback (most recent call last):
  File "DFIRtriage-v5-pub.py", line 885, in <module>
  File "DFIRtriage-v5-pub.py", line 399, in network_data_gathering
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Windows\\SysWOW64/cports.html' -> 'XXXXXXX.20220415073447/LiveResponseData/NetworkInfo/cports.html'
[3968] Failed to execute script DFIRtriage-v5-pub

Leaving no output folder.

(Tested on the latest Windows 11 environment)

**Comment by travisfoley** [comment] 2023-12-15 02:39
See if the issue is resolved in v6.0.  Just updated repo

**Comment by travisfoley** [comment] 2024-03-25 13:10
New version released.

**Closed as completed by travisfoley** 2024-03-25 13:10 UTC
